spring:
  application:
    name: sleeping
  jpa:
    hibernate:
          ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PW}

# auth
secret:
  key : ${SECRET_KEY}
  access:
    expiry: ${ACCESS_TOKEN_EXPIRY}
  refresh:
    expiry: ${REFRESH_TOKEN_EXPIRY}

# influxDB
influxdb:
  url: ${INFLUX_URL}
  org: ${INFLUX_ORG}
  bucket: ${INFLUX_BUCKET}
  token: ${INFLUX_TOKEN}