name: Spring Boot CI/CD with Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout 코드
      - name: Checkout 코드
        uses: actions/checkout@v3

      # Step 2: JDK 17 설정
      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Step 3: Gradle 캐시 설정
      - name: Gradle 캐시
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Step 4: Gradle 빌드 (--scan으로 디버깅)
      - name: Gradle 빌드
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ACCESS_TOKEN_EXPIRY: ${{ secrets.ACCESS_TOKEN_EXPIRY }}
          REFRESH_TOKEN_EXPIRY: ${{ secrets.REFRESH_TOKEN_EXPIRY }}
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PW: ${{ secrets.MYSQL_PW }}
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
          INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --scan --info --no-daemon
        continue-on-error: true

      # Step 5: 테스트 보고서 업로드
      - name: 테스트 보고서 업로드
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test/

      # Step 6: Gradle 스캔 보고서 URL 출력
      - name: Gradle 스캔 URL 출력
        if: always()
        run: |
          echo "Gradle scan report URL (if generated):"
          cat build/scan.log || echo "No scan report generated"

      # Step 7: Docker Hub 로그인
      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Docker 이미지 빌드 및 푸시
      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring_app:latest
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ACCESS_TOKEN_EXPIRY=${{ secrets.ACCESS_TOKEN_EXPIRY }}
            REFRESH_TOKEN_EXPIRY=${{ secrets.REFRESH_TOKEN_EXPIRY }}
            MYSQL_URL=${{ secrets.MYSQL_URL }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PW=${{ secrets.MYSQL_PW }}
            INFLUX_URL=${{ secrets.INFLUX_URL }}
            INFLUX_ORG=${{ secrets.INFLUX_ORG }}
            INFLUX_BUCKET=${{ secrets.INFLUX_BUCKET }}
            INFLUX_TOKEN=${{ secrets.INFLUX_TOKEN }}

      # Step 9: 서버 배포
      - name: 서버 배포
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 기존 컨테이너 중지 및 제거
            docker stop spring_app || true
            docker rm spring_app || true
            # 최신 이미지 풀
            docker pull ${{ secrets.DOCKER_USERNAME }}/spring_app:latest
            # Docker 네트워크 확인 및 생성
            docker network create app-network || true
            # MySQL과 InfluxDB 컨테이너 네트워크 연결
            docker network connect app-network mysql-container || true
            docker network connect app-network influxdb || true
            # 새 컨테이너 실행
            docker run -d --name spring_app \
              --network app-network \
              -p 88:8080 \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e ACCESS_TOKEN_EXPIRY=${{ secrets.ACCESS_TOKEN_EXPIRY }} \
              -e REFRESH_TOKEN_EXPIRY=${{ secrets.REFRESH_TOKEN_EXPIRY }} \
              -e MYSQL_URL=${{ secrets.MYSQL_URL }} \
              -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
              -e MYSQL_PW=${{ secrets.MYSQL_PW }} \
              -e INFLUX_URL=${{ secrets.INFLUX_URL }} \
              -e INFLUX_ORG=${{ secrets.INFLUX_ORG }} \
              -e INFLUX_BUCKET=${{ secrets.INFLUX_BUCKET }} \
              -e INFLUX_TOKEN=${{ secrets.INFLUX_TOKEN }} \
              ${{ secrets.DOCKER_USERNAME }}/spring_app:latest
