name: Spring Boot CI/CD

on:
  push:
    branches:
      - feat/user-detail
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout 코드
      - name: Checkout 코드
        uses: actions/checkout@v3

      # Step 2: JDK 17 설정
      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Step 3: Gradle 캐시 설정
      - name: Gradle 캐시
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Step 4: 환경 변수 디버깅
      - name: 환경 변수 확인
        run: |
          echo "SECRET_KEY is set to: ${{ secrets.SECRET_KEY }}"
          echo "MYSQL_URL is set to: ${{ secrets.MYSQL_URL }}"
          if [ -z "${{ secrets.SECRET_KEY }}" ]; then
            echo "Error: SECRET_KEY is empty or not set"
            exit 1
          fi
          if [ -z "${{ secrets.MYSQL_URL }}" ]; then
            echo "Error: MYSQL_URL is empty or not set"
            exit 1
          fi

      # Step 5: Gradle 빌드 (테스트 건너뛰기)
      - name: Gradle 빌드
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ACCESS_TOKEN_EXPIRY: ${{ secrets.ACCESS_TOKEN_EXPIRY }}
          REFRESH_TOKEN_EXPIRY: ${{ secrets.REFRESH_TOKEN_EXPIRY }}
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PW: ${{ secrets.MYSQL_PW }}
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
          INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test --no-daemon

      # Step 6: Docker Hub 로그인
      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: DOCKER_USERNAME 디버깅
      - name: DOCKER_USERNAME 확인
        run: |
          echo "DOCKER_USERNAME is set to: ${{ secrets.DOCKER_USERNAME }}"
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Error: DOCKER_USERNAME is empty or not set"
            exit 1
          fi

      # Step 8: Docker 이미지 빌드 및 푸시
      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            parkminjin/spring_app:latest
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ACCESS_TOKEN_EXPIRY=${{ secrets.ACCESS_TOKEN_EXPIRY }}
            REFRESH_TOKEN_EXPIRY=${{ secrets.REFRESH_TOKEN_EXPIRY }}
            MYSQL_URL=${{ secrets.MYSQL_URL }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PW=${{ secrets.MYSQL_PW }}
            INFLUX_URL=${{ secrets.INFLUX_URL }}
            INFLUX_ORG=${{ secrets.INFLUX_ORG }}
            INFLUX_BUCKET=${{ secrets.INFLUX_BUCKET }}
            INFLUX_TOKEN=${{ secrets.INFLUX_TOKEN }}

      # Step 9: SSH 설정 확인
      - name: SSH 설정 확인
        run: |
          echo "SSH_HOST is set to: ${{ secrets.SSH_HOST }}"
          echo "SSH_USER is set to: ${{ secrets.SSH_USER }}"
          echo "SSH_PORT is set to: ${{ secrets.SSH_PORT }}"
          echo "SSH_PASSWORD is set: ${{ secrets.SSH_PASSWORD != '' }}"
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "Error: SSH_HOST is empty or not set"
            exit 1
          fi
          if [ -z "${{ secrets.SSH_USER }}" ]; then
            echo "Error: SSH_USER is empty or not set"
            exit 1
          fi
          if [ -z "${{ secrets.SSH_PASSWORD }}" ]; then
            echo "Error: SSH_PASSWORD is empty or not set"
            exit 1
          fi

      # Step 10: 서버 배포 (비밀번호 인증)
      - name: 서버 배포
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} '
            # Docker Hub 로그인
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            # 기존 컨테이너 중지 및 제거
            docker stop spring_app || true
            docker rm spring_app || true
            # 최신 이미지 풀
            docker pull parkminjin/spring_app:latest
            # Docker 네트워크 확인 및 생성
            docker network create app-network || true
            # MySQL과 InfluxDB 컨테이너 네트워크 연결
            docker network connect app-network mysql-container || true
            docker network connect app-network influxdb || true
            # 새 컨테이너 실행
            docker run -d --name spring_app \
              --network app-network \
              -p 88:8080 \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e ACCESS_TOKEN_EXPIRY=${{ secrets.ACCESS_TOKEN_EXPIRY }} \
              -e REFRESH_TOKEN_EXPIRY=${{ secrets.REFRESH_TOKEN_EXPIRY }} \
              -e MYSQL_URL=${{ secrets.MYSQL_URL }} \
              -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
              -e MYSQL_PW=${{ secrets.MYSQL_PW }} \
              -e INFLUX_URL=${{ secrets.INFLUX_URL }} \
              -e INFLUX_ORG=${{ secrets.INFLUX_ORG }} \
              -e INFLUX_BUCKET=${{ secrets.INFLUX_BUCKET }} \
              -e INFLUX_TOKEN=${{ secrets.INFLUX_TOKEN }} \
              parkminjin/spring_app:latest
          '
