name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: be-1  # Azure Web App 이름
  DOCKER_IMAGE_TAG: latest # Docker 이미지 태그

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: parkminjin/spring_app:${{ env.DOCKER_IMAGE_TAG }}
          file: ./Dockerfile
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ACCESS_TOKEN_EXPIRY=${{ secrets.ACCESS_TOKEN_EXPIRY }}
            REFRESH_TOKEN_EXPIRY=${{ secrets.REFRESH_TOKEN_EXPIRY }}
            MYSQL_URL=${{ secrets.MYSQL_URL }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PW=${{ secrets.MYSQL_PW }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: parkminjin/spring_app:${{ env.DOCKER_IMAGE_TAG }}
