# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - be-1

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_35aade6005864e2a98455b2af80bdb4d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6aea0841c23642699b31f96feebd4225 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_35aade6005864e2a98455b2af80bdb4d }}/parkminjin/spring_app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'be-1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_61f0e8a3de214fc8bdcfe9d6c1d9b018 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_35aade6005864e2a98455b2af80bdb4d }}/parkminjin/spring_app:${{ github.sha }}'