name: Build and deploy JAR app to Azure Web App - be-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: List built files
        run: ls -la build/libs/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/sleeping-0.0.1-SNAPSHOT.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List downloaded files
        run: ls -la

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'be-1'
          slot-name: 'Production'
          package: 'sleeping-0.0.1-SNAPSHOT.jar'  # 명시적으로 JAR 파일 지정
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_671764E7AE5C479CAA9DCD1A9CA0DA81 }}
          startup-command: 'java -Duser.timezone=GMT+9 -Djava.security.egd=file:/dev/./urandom -jar /site/wwwroot/sleeping-0.0.1-SNAPSHOT.jar'

env:
  ACTIONS_STEP_DEBUG: true
  MYSQL_URL: ${{ secrets.MYSQL_URL }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PW: ${{ secrets.MYSQL_PW }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ACCESS_TOKEN_EXPIRY: ${{ secrets.ACCESS_TOKEN_EXPIRY }}
  REFRESH_TOKEN_EXPIRY: ${{ secrets.REFRESH_TOKEN_EXPIRY }}
  INFLUX_URL: ${{ secrets.INFLUX_URL }}
  INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
  INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
  INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
